[package]
name = "rust-async-otel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.2.1"
awc = "3.0.1"
tokio = "1.22.0"
